# frozen_string_literal: true

class LoadTestNotification < AbstractNotification
  notification_type "load_test"
  idempotency_window 1.second

  def self.title(_ctx = {})
    "Load test notification"
  end

  def self.body(_ctx = {})
    "Generated by load test scenario."
  end
end
