module MetricsAuth
  USER     = ENV["METRICS_BASIC_AUTH_USER"]
  PASSWORD = ENV["METRICS_BASIC_AUTH_PASSWORD"]

  CREDENTIALS_PRESENT = USER.present? && PASSWORD.present?
  CREDENTIALS = [ USER, PASSWORD ].freeze
end
