name: Security

on:
  pull_request:
  push:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Brakeman
        run: bundle exec brakeman --no-pager --confidence-level 2 --exit-on-warn --ignore-config config/brakeman.ignore
      - name: Bundler Audit
        run: bundle exec bundle-audit check --update
